version: "3.8"

services:
  app:
    build: .
    container_name: ums_app
    network_mode: "host"
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "base64:8jMJVmFmwHQnnj63uBR6xfa/qk251M7NIX36V/Ry0+k="
  # MySQL database service
  mysql:
    image: mysql:8.0
    container_name: osums_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 2010
      MYSQL_DATABASE: homestead
      MYSQL_USER: root
      MYSQL_PASSWORD: 2010
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
